print(3+4)
print(3-4)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)
print('lucia')
print('Rojas')
print('España')
print('i am enjoying 30 days of python')
print(types(10))
print(types(9.8))
print(types(3.14))
print(types(4 4j))
print(types("lucia"))
print(types("rojas"))
print(types("españa"))
print(types['Lucia','Rojas','españa'])
print(28)
print(5.4)
print(5+l)
print(i love Louis Tomlinson)
print(True)#Is the light on? If it is on, then the value is True
print(False)#Is the light on? If it is off, then the value is False
print[0, 1, 2]