age = 16
height = 1,71
store = 2+j
base = input ("cual es el area")
height_triangle = input ("cual es el area")
area_of_the_triangle = 0.5 * base * height_triangle
side_a = input ("cual es el perimetro")
side_b = input ("cual es el perimetro")
side_c = input ("cual es el perimetro")
perimeter_of_the_trianlge = side_a + side_b + side_c
length = input ("cueales son el area y perimetro")
width = input ("cuales son el area y perimetro")
area = length * width
perimeter = 2 * (length + width)
pi = 3.14
r = input ("cuales son el area y circunferencia")
area = pi * r * r
circunference = 2 * pi * r
m = input ("cual es la y")
x = input ("cual es la y")
b = input ("cual es la y")
y = m * x + base
y1 = 2
x1 = 2
x2 = 6
y2 = 10
m = y2 - y1 / x2 - x1
"comparar la pendiente"(m1 == m2)
x3 = input ("que valor de x y es 0")
y = x3 ^2 + 6 * ^3 + 9